/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 brain.glb -K -k
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export function Brain(props) {
  const { nodes, materials } = useGLTF("models/brain.glb");

  // // Set the gray color for all materials
  // Object.values(materials).forEach((material) => {
  //   material.color.set(0.5, 0.5, 0.5); // Set RGB values to achieve gray color
  // });

  const whiteWireframeMaterial = useRef(
    new THREE.MeshBasicMaterial({
      color: 0x6c6c6c,
      wireframe: true,
    })
  );

  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model">
          <group name="brainpartsobjcleanermaterialmergergles">
            <mesh
              name="BluePart"
              geometry={nodes.BluePart.geometry}
              // material={materials["Material.004"]}
              material={whiteWireframeMaterial.current}
            />
            <mesh
              name="GreenPart"
              geometry={nodes.GreenPart.geometry}
              // material={materials["Material.002"]}
              material={whiteWireframeMaterial.current}
            />
            <mesh
              name="RedPart"
              geometry={nodes.RedPart.geometry}
              // material={materials["Material.001"]}
              material={whiteWireframeMaterial.current}
            />
            <mesh
              name="VioletPart"
              geometry={nodes.VioletPart.geometry}
              // material={materials["Material.005"]}
              material={whiteWireframeMaterial.current}
            />
            <mesh
              name="WhitePart"
              geometry={nodes.WhitePart.geometry}
              // material={materials.material_0}
              material={whiteWireframeMaterial.current}
            />
            <mesh
              name="YellowPart"
              geometry={nodes.YellowPart.geometry}
              // material={materials["Material.003"]}
              material={whiteWireframeMaterial.current}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/brain.glb");
